### ISSUE TITLE
Is the provider still active ?

### ISSUE THREAD

**Issue by aelbarkani** [openshift/machine-api-provider-kubevirt#44]
Hi !

It would be great to keep this provider in order to be able to provision OpenShift clusters inside OpenShift as explained here https://cloud.redhat.com/blog/nested-openshift-using-openshift-virtualization, but will this provider be maintained further ? I've seen that kubevirt support has been removed from the installer https://github.com/openshift/installer/pull/5301, so I was wondering whether this provider will have the same fate (I hope not:)).

**Comment by fabiand** [comment]
No.

@bardielle can you help to archive this repository?

**Comment by fabiand** [comment]
cc @chenyosef

**Comment by bardielle** [comment]
I don't have permission to archive that repo, also I tried to curl collaborators  but I don't have the right permissions....

**Comment by chenyosef** [comment]
Archiving this repo
